// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRunnable is an autogenerated mock type for the Runnable type
type MockRunnable struct {
	mock.Mock
}

type MockRunnable_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRunnable) EXPECT() *MockRunnable_Expecter {
	return &MockRunnable_Expecter{mock: &_m.Mock}
}

// RunWithContext provides a mock function with given fields: _a0
func (_m *MockRunnable) RunWithContext(_a0 context.Context) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for RunWithContext")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRunnable_RunWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunWithContext'
type MockRunnable_RunWithContext_Call struct {
	*mock.Call
}

// RunWithContext is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockRunnable_Expecter) RunWithContext(_a0 interface{}) *MockRunnable_RunWithContext_Call {
	return &MockRunnable_RunWithContext_Call{Call: _e.mock.On("RunWithContext", _a0)}
}

func (_c *MockRunnable_RunWithContext_Call) Run(run func(_a0 context.Context)) *MockRunnable_RunWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRunnable_RunWithContext_Call) Return(_a0 error) *MockRunnable_RunWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRunnable_RunWithContext_Call) RunAndReturn(run func(context.Context) error) *MockRunnable_RunWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRunnable creates a new instance of MockRunnable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRunnable(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRunnable {
	mock := &MockRunnable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
